-- =============================================
-- Migration 002: AI Auto-Marketing System
-- Run in Supabase SQL Editor
-- =============================================

-- 1. Blog posts (public SEO content auto-generated by AI)
CREATE TABLE IF NOT EXISTS blog_posts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    excerpt TEXT NOT NULL,
    content TEXT NOT NULL, -- markdown
    keywords TEXT[] DEFAULT '{}',
    meta_description TEXT,
    cover_image TEXT,
    status TEXT DEFAULT 'published' CHECK (status IN ('draft', 'published', 'archived')),
    reading_time_minutes INTEGER DEFAULT 3,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    published_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_blog_posts_status ON blog_posts(status);
CREATE INDEX IF NOT EXISTS idx_blog_posts_published_at ON blog_posts(published_at DESC);

-- 2. Social media drafts (AI-generated content for manual posting)
CREATE TABLE IF NOT EXISTS social_posts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    platform TEXT NOT NULL CHECK (platform IN ('reddit', 'facebook', 'g2', 'twitter', 'linkedin')),
    subreddit TEXT, -- e.g. 'r/doggrooming' for reddit
    title TEXT,
    content TEXT NOT NULL,
    target_keyword TEXT,
    used BOOLEAN DEFAULT false,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_social_posts_used ON social_posts(used, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_social_posts_platform ON social_posts(platform);

-- 3. RLS: blog posts are public-readable
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read published blog posts"
    ON blog_posts FOR SELECT
    USING (status = 'published');

-- 4. RLS: social posts are user-private (only their own shop)
-- Note: social posts are global for now since marketing is shared content
ALTER TABLE social_posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated can read social posts"
    ON social_posts FOR SELECT
    TO authenticated
    USING (true);